credentials:
  usernames:
    admin:
      name: Family Admin
      email: admin@family.com
      password: "$2b$12$uwjJlq61GEhdCM7CrOWVYu/.3wI4j1wxIFYwXiiAC4eNALg0jJykS"
cookie:
  expiry_days: 30
  key: "random_signature_key_secure"
  name: "family_finance_cookie"
preauthorized:
  emails:
    - admin@family.com
